url: https://palakmathur.in
title: Palak Mathur 
email: insanethoughts@live.com
author: Palak Mathur
description: > # Palak Mathur is no more anonymous
copyright: 'Copyright &copy; 2021 Palak Mathur. All Rights Reserved.'

markdown: kramdown
permalink: pretty

# Include well-known assets in the built site
include:
  - .well-known

social:
 
  - title: blog
    url: https://systemhalted.in
    type: solid
  - title: podcast
    url: https://podcasts.apple.com/us/podcast/nukkad-shukkad/id1537261609
    type: solid
  - title: spotify
    url: https://open.spotify.com/show/35GJ2PUl23E4LeFLRuFBl6
    type: brands
  - title: github
    url: https://github.com/systemhalted
    type: brands
  - title: linkedin
    url: https://www.linkedin.com/in/systemhalted/
    type: brands
  - title: twitter
    url: https://twitter.com/palak
    type: brands
  - title: instagram
    url: https://www.instagram.com/palak_clicks/
    type: brands
  - title: bookmark
    url: https://pinboard.in/u:systemhalted
    type: solid
  - title: book
    url: https://www.librarycat.org/lib/palakmathur
    type: solid
  - title: mastodon
    url: https://fosstodon.org/@squeamishossifrage
    type: brands
